### ISSUE TITLE
ePub

### ISSUE THREAD

**Issue by Matthias84** [gitbuch/gitschulung_cc#1]
So eine ePub-Version wäre echt schick. Dann kann man die immer mitnehmen, denn ab und zu hat man ja doch Konstellationen die man nicht überblickt und wo ein cheatsheet zu kurz greift.

**Comment by esc** [comment]
Für die Folien, ja?

**Comment by Matthias84** [comment]
Ich dachte eigentlich an das Buch. Derzeit ist das mit den HTML-Seiten leider nicht so transportabel.

**Comment by Feh** [comment]
Du hast auf dem Repository der Folien kommentiert, daher Valentins Frage. Das Git-Buch hat seit https://github.com/gitbuch/gitbuch_cc/pull/2 auch EPUB-Support. Einfach `make epub` eingeben.

**Comment by Matthias84** [comment]
@Feh @esc  Entschuldigt bitte, da war ich wohl etwas zu fix!

**Comment by Feh** [comment]
Kein Problem. Ich verlinke nachher noch eine EPUB- und PDF-Version von der Startseite von http://gitbu.ch/…
